lib/ueberauth_example_web/router.ex
defmodule UeberauthExampleWeb.Router do
  @moduledoc false

  use UeberauthExampleWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/auth", UeberauthExampleWeb do
    pipe_through :browser

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
    delete "/logout", AuthController, :delete
  end

  scope "/", UeberauthExampleWeb do
    pipe_through :browser

    get "/", PageController, :index
  end
end

lib/ueberauth_example/application.ex
defmodule UeberauthExample.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    children = [
      # Start the Telemetry supervisor
      UeberauthExampleWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: UeberauthExample.PubSub},
      # Start the Endpoint (http/https)
      UeberauthExampleWeb.Endpoint
      # Start a worker by calling: UeberauthExample.Worker.start_link(arg)
      # {UeberauthExample.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: UeberauthExample.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    UeberauthExampleWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/ueberauth_example/user_from_auth.ex
defmodule UeberauthExample.UserFromAuth do
  @moduledoc """
  Retrieve the user information from an auth request
  """
  require Logger
  require Jason

  alias Ueberauth.Auth

  def find_or_create(%Auth{provider: :identity} = auth) do
    case validate_pass(auth.credentials) do
      :ok ->
        {:ok, basic_info(auth)}

      {:error, reason} ->
        {:error, reason}
    end
  end

  def find_or_create(%Auth{} = auth) do
    {:ok, basic_info(auth)}
  end

  # github does it this way
  defp avatar_from_auth(%{info: %{urls: %{avatar_url: image}}}), do: image

  # facebook does it this way
  defp avatar_from_auth(%{info: %{image: image}}), do: image

  # default case if nothing matches
  defp avatar_from_auth(auth) do
    Logger.warn("#{auth.provider} needs to find an avatar URL!")
    Logger.debug(Jason.encode!(auth))
    nil
  end

  defp basic_info(auth) do
    %{id: auth.uid, name: name_from_auth(auth), avatar: avatar_from_auth(auth)}
  end

  defp name_from_auth(auth) do
    if auth.info.name do
      auth.info.name
    else
      name =
        [auth.info.first_name, auth.info.last_name]
        |> Enum.filter(&(&1 != nil and &1 != ""))

      if Enum.empty?(name) do
        auth.info.nickname
      else
        Enum.join(name, " ")
      end
    end
  end

  defp validate_pass(%{other: %{password: nil}}) do
    {:error, "Password required"}
  end

  defp validate_pass(%{other: %{password: pw, password_confirmation: pw}}) do
    :ok
  end

  defp validate_pass(%{other: %{password: _}}) do
    {:error, "Passwords do not match"}
  end

  defp validate_pass(_), do: {:error, "Password Required"}
end

lib/ueberauth_example_web/controllers/auth_controller.ex
defmodule UeberauthExampleWeb.AuthController do
  @moduledoc """
  Auth controller responsible for handling Ueberauth responses
  """

  use UeberauthExampleWeb, :controller

  plug Ueberauth

  alias Ueberauth.Strategy.Helpers
  alias UeberauthExample.UserFromAuth

  def request(conn, _params) do
    render(conn, "request.html", callback_url: Helpers.callback_url(conn))
  end

  def delete(conn, _params) do
    conn
    |> put_flash(:info, "You have been logged out!")
    |> clear_session()
    |> redirect(to: "/")
  end

  def callback(%{assigns: %{ueberauth_failure: _fails}} = conn, _params) do
    conn
    |> put_flash(:error, "Failed to authenticate.")
    |> redirect(to: "/")
  end

  def callback(%{assigns: %{ueberauth_auth: auth}} = conn, _params) do
    case UserFromAuth.find_or_create(auth) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "Successfully authenticated.")
        |> put_session(:current_user, user)
        |> configure_session(renew: true)
        |> redirect(to: "/")

      {:error, reason} ->
        conn
        |> put_flash(:error, reason)
        |> redirect(to: "/")
    end
  end
end

lib/ueberauth_example_web/controllers/page_controller.ex
defmodule UeberauthExampleWeb.PageController do
  @moduledoc """
  Static page controller
  """

  use UeberauthExampleWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html", current_user: get_session(conn, :current_user))
  end
end

lib/ueberauth_example_web/views/auth_view.ex
defmodule UeberauthExampleWeb.AuthView do
  @moduledoc false

  use UeberauthExampleWeb, :view
end

lib/ueberauth_example_web/views/error_view.ex
defmodule UeberauthExampleWeb.ErrorView do
  use UeberauthExampleWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/ueberauth_example_web/views/layout_view.ex
defmodule UeberauthExampleWeb.LayoutView do
  use UeberauthExampleWeb, :view
end

lib/ueberauth_example_web/views/page_view.ex
defmodule UeberauthExampleWeb.PageView do
  use UeberauthExampleWeb, :view
end

lib/ueberauth_example_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Überauth Example</title>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav>
          <ul>
          <li>
            <a href="https://github.com/ueberauth/ueberauth_example">
              <i class="fa fa-github"></i>
              View on GitHub
            </a>
          </li>
          </ul>
        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>

lib/ueberauth_example_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1>Überauth + Phoenix Example</h1>
  <p>
    This is an application to show an example of how to wire up
    <a href="https://github.com/ueberauth/ueberauth">Überauth</a> with
    <a href="https://github.com/phoenixframework/phoenix">Phoenix</a>.
  </p>
  <%= if @current_user do %>
    <h2>Welcome, <%= @current_user.name %>!</h2>
    <div>
      <img src="<%= @current_user.avatar %>" />
    </div>
    <%= link "Logout", to: Routes.auth_path(@conn, :delete), method: "delete", class: "button" %>
    <br>
  <% else %>
    <ul style="list-style: none">
      <li>
        <a class="button" href="<%= Routes.auth_path(@conn, :request, "github") %>">
          <i class="fa fa-github"></i>
          Sign in with GitHub
        </a>
      </li>
      <li>
        <a class="button" href="<%= Routes.auth_path(@conn, :request, "facebook") %>">
        <i class="fa fa-facebook"></i>
        Sign in with Facebook
        </a>
      </li>
      <li>
        <a class="button" href="<%= Routes.auth_path(@conn, :request, "google") %>">
        <i class="fa fa-google"></i>
        Sign in with Google
        </a>
      </li>
      <li>
        <a class="button" href="<%= Routes.auth_path(@conn, :request, "slack") %>">
        <i class="fa fa-slack"></i>
        Sign in with Slack
        </a>
      </li>
      <li>
        <a class="button" href="<%= Routes.auth_path(@conn, :request, "twitter") %>">
        <i class="fa fa-twitter"></i>
        Sign in with Twitter
        </a>
      </li>
      <li>
        <a class="button" href="<%= Routes.auth_path(@conn, :request, "identity") %>">
        <i class="fa fa-user"></i>
        Sign in with Username/Password
        </a>
      </li>
      <li>
        <a class="button" href="<%= Routes.auth_path(@conn, :request, "okta") %>">
        <i class="fa fa-user"></i>
        Sign in with Okta
        </a>
      </li>
    </ul>
  <% end %>
</section>